const express = require('express')
const router = express.Router()
const loginRoute = require('../../modules/auth/login/routes/login.route')
const registerRoute = require('../../modules/auth/register/routes/register.route')
const memberProfileRoute = require('../../modules/member/profile/routes/profile.route')
const publicGenreRoute = require('../../modules/public/genre/routes/genre.route')
const publicBookRoute = require('../../modules/public/book/routes/book.route')
const publicProvinceRoute = require('../../modules/public/location/province/routes/province.route')
const publicCityRoute = require('../../modules/public/location/city/routes/city.route')
const officerGenreRoute = require('../../modules/officer/genre/routes/genre.route')
const officerBookRoute = require('../../modules/officer/book/routes/book.route')
const officerMemberRoute = require('../../modules/officer/member/routes/member.route')

router.use('/auth', loginRoute)
router.use('/auth', registerRoute)
router.use('/genres', publicGenreRoute)
router.use('/books', publicBookRoute)
router.use('/provinces', publicProvinceRoute)
router.use('/cities', publicCityRoute)
router.use('/officer/genres', officerGenreRoute)
router.use('/officer/books', officerBookRoute)
router.use('/officer/members', officerMemberRoute)
router.use('/member/profile', memberProfileRoute)

module.exports = router